### PR TITLE
Custom assets may be injected by defining their paths in the config

### PR DESCRIPTION
**Pull request by mdcass**
Hi,

# Requirement

I required the ability to add custom assets to the base layout

## Notes

* I appreciate this functionality could cover a broad scope, I opted for a simple implementation to start with
* I wasn't sure whether the documentation should live in the place that i've put it, open to suggestions
* I wasn't sure whether there would be implications with including the view composer in [all views](https://github.com/mdcass/sharp/commit/bda06dc4b50d5bee2b246763ca2b5b086729abae#diff-e6e21d24614b09ab3bfa2d2ce37af9f9R53)
* I wasn't sure what the best location for a test would be
* The current test doesn't cover injecting assets using the Laravel `asset()` or `mix()` functions, as I felt attempting to mock those may make the tests lengthy and obsolete when they're a core part of the framework

Feedback appreciated!

### CODE REVIEW

**Comment by dvlpp** [comment]
This is an interesting solution, thanks for this. I thought of something similar, but I felt this could easily lead to front issues on Sharp, like CSS collisions for instance. 

Of course it would be the developer responsibility to write custom assets carefully, but it could be more complex when updating Sharp. Maybe we should provide more stability in the CSS class naming — even if we are already using a kind of BEM standard.

@aguingand, what's your feeling about this?

@mdcass, I'm curious: what is your original issue/need you are addressing with this PR?

**Comment by mdcass** [comment]
Yeah I understand.

It would be nice to be able to inject custom Vue components around the place and customise CSS through SASS, but it seems like it would be a major bit of work.

Happy to park this for now, although it has been useful for me for customising the look of our admin panel, just got to be mindful to avoid class conflicts.

**Comment by mdcass** [comment]
Sounds good, i'll refactor out the JS injection, rebase and force push!

**Comment by mdcass** [comment]
I've added a small change to the `sharp.js` asset which was part of the previous pull request (link command) but I missed off the compiled JS (sorry!)

**Comment by dvlpp** [comment]
Thanks for your contribution, @mdcass!

**Pull request merged**
