### PR TITLE
Package helpers should be able to be overridden

### PR DESCRIPTION
**Pull request by thenabeel**
Sharp helpers should be able to be overridden.
Currently it is not possible.
Code changes done in the PR will create the ability to override Sharp helpers when required. Then users can override any helper in their own helpers files.

### CODE REVIEW

**Comment by dvlpp** [comment]
Mmm, these helpers are really specific to Sharp, used for internal functionalities; I think of them as private helpers... I mean, we try to avoid breaking changes between versions, but we don't intend to include in this promise internal helpers like these. Overriding an helper might not work anymore on an update without any BC documented... But maybe I'm missing something: why do you need this feature?

**Comment by dvlpp** [comment]
I see. In this case, yes, a config seems to be the good way to achieve this. Maybe we could have something more generic, with a default value, like `config('sharp.name_in_page_title', 'sharp')`? This `sharp_page_title()` helper seems quite bad to me, to be honest, and it would break in a multi-form case. I think it needs a global refactoring...

**Comment by dvlpp** [comment]
I'll look closer in a few hours; I keep you in touch here.

**Comment by thenabeel** [comment]
Thanks mate!

**Pull request closed without merging**
