### PR TITLE
Fix model wizard calling create list class command

### PR DESCRIPTION
**Pull request by earboxer**

### CODE REVIEW

**Comment by dvlpp** [comment]
Thanks for that. I'll merge it as soon as we fix front test issue that prevents Travis to pass.

**Comment by dvlpp** [comment]
Could you please merge master in this PR to ensure everything passes now that we've fixed front tests (for Travis)?

**Comment by earboxer** [comment]
I did that, and it passes now :)

Maybe we should consider adding tests for the model wizard command. Are there any tests for existing artisan commands?

**Comment by dvlpp** [comment]
No, we've got no test on artisan make commands; they were added recently by a community PR (#66), but without tests—I'm not really sure they are really necessary, since it's development sugar, it won't affect production code.

**Pull request merged**
