### PR TITLE
Menu

### PR DESCRIPTION
**Pull request by trister1997**
Hey, I love the library but I noticed that it was missing some features I need such as a single page link, and I saw someone else requested external links in the navigation in issue #26 so I added these features. I hope my code is okay, I will be happy to fix whatever I need, and if this cant be merged, I would be happy to just maintain and use my own fork :) Awesome work on the project!
Here is a example of the new menu array:
```
"menu" => [
        [
            "type" => "external",
            "entity" => "google",
            "properties" => [
                "label" => "External Test",
                "icon" => "fa-globe",
                "url" => "https://google.com"
            ]
        ],
        [
            "type" => "page",
            "entity" => "spaceship",
            "properties" => [
                "label" => "Solo Spaceship",
                "icon" => "fa-folder"
            ]
        ],
        [
            "type" => "category",
            "entities" => [
                "projects" => [
                    "label" => "Projects",
                    "icon" => "fa-folder"
                ]
            ],
            "label" => "Projects"
        ]
    ]
```

### CODE REVIEW

**Comment by dvlpp** [comment]
Thanks for your contribution. 

I think that generalizing to menu items is a good idea. I haven't tested the code yet, but before that I think the way to configure items could be easier to read, and more consistent. Maybe by dropping types (determined by the presence of `url`, `entity` or `entities`), and dropping unneeded `attributes` node... something like this:

    "menu" => [
        [
            "label" => "External Test",
            "icon" => "fa-globe",
            "url" => "https://google.com"
        ],
        [
            "label" => "Solo Spaceship",
            "icon" => "fa-folder",
            "entity" => "spaceship"
        ],
        [
            "label" => "Projects",
            "entities" => [
                [
                    "label" => "Projects",
                    "icon" => "fa-folder",
                    "entity" => "project"
                ]
            ]
        ]
    ]

Plus, this would be back-compatible with the current Sharp version. What's your opinion on this?

I still have to test the real implementation, to see how this feel (and look): maybe you could add a example of this in the "Saturn" project, the testing app in the repo?

**Comment by trister1997** [comment]
@dvlpp yep I can do that! Ill push in a couple hours.

**Comment by trister1997** [comment]
@dvlpp I just added another commit, with this commit I came across a scenario where I wanted to link directly to a form in the menu. For an example use case, I want a person to be able to configure some attributes such as their name and some social links, which would use a profile_attributes table with a name and a value as the columns. This needs to be just a form with no list and I wanted to link directly to that. Let me know if that makes sense, or for my scenario, if you have an idea of how to do it a better way so that this form linking is not needed. all this would add is an optional key to each menu item array called "link_type" with the value of form or list.

**Comment by dvlpp** [comment]
OK, this seems great. I checked this locally, I would like to modify some details, mostly on the front side, to fix tests and other things. I plan to do that in the coming days. 
But since the config file is good this way, I think you are safe to use your version for now.

**Comment by dvlpp** [comment]
This feature was extracted in its own PR and merged here: #46

**Pull request closed without merging**
